apiVersion: v1
kind: Service
metadata:
  name: arithmatic-service
spec:
  selector:
    app: arithmatic
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arithmatic
spec:
  selector:
    matchLabels:
      app: arithmatic
  replicas: 4
  template:
    metadata:
      labels:
        app: arithmatic
    spec:
      containers:
      - name: arithmatic
        image: apoorvtyagi/arithmatic:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000